import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Local todo&apos;s</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hey!</h1>
      </main>
    </div>
  );
}
